package com.hiddenhistory.models

import kotlinx.serialization.InternalSerializationApi
import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

// --- Data Models ---

@OptIn(InternalSerializationApi::class)
@Serializable
data class Vehicle(
    @SerialName("registrationNumber") val registrationNumber: String? = null,
    @SerialName("make") val make: String? = null,
    @SerialName("model") val model: String? = null,
    @SerialName("mileage") val mileage: Int? = null,
    @SerialName("yearOfManufacture") val year: Int? = null,
    @SerialName("taxStatus") val taxStatus: String? = null,
    @SerialName("fuelType") val fuelType: String? = null,
    @SerialName("hasOutstandingRecall") val hasOutstandingRecall: String? = null,
    @SerialName("salvageCategory") val salvageCategory: String? = null,
    @SerialName("vehicleTier") val vehicleTier: String? = null,
    @SerialName("motTests") val motTests: List<MotTest> = emptyList(),
    @SerialName("activeSymptoms") val activeSymptoms: List<SymptomReport> = emptyList(),
    @SerialName("taxDueDate") val taxDueDate: String? = null,
    @SerialName("motStatus") val motStatus: String? = null,
    @SerialName("engineCapacity") val engineCapacity: Int? = null,
    @SerialName("co2Emissions") val co2Emissions: Int? = null,
    @SerialName("colour") val colour: String? = null,
    @SerialName("primaryColour") val primaryColour: String? = null,
    @SerialName("typeApproval") val typeApproval: String? = null,
    @SerialName("dateOfLastV5CIssued") val dateOfLastV5CIssued: String? = null,
    @SerialName("wheelplan") val wheelplan: String? = null,
    @SerialName("monthOfFirstRegistration") val monthOfFirstRegistration: String? = null,
    @SerialName("registrationDate") val registrationDate: String? = null,
    @SerialName("manufactureDate") val manufactureDate: String? = null,
    @SerialName("firstUsedDate") val firstUsedDate: String? = null,
    @SerialName("previousKeepers") val previousKeepers: Int? = null,
    @SerialName("vin") val vin: String? = null,
    @SerialName("previousOwners") val previousOwners: Int? = null,
    @SerialName("seats") val seats: Int? = null,
    @SerialName("price") val price: Double? = null,
    @SerialName("maxTowWeight") val maxTowWeight: Double? = null,
    @SerialName("motExpiryDate") val motExpiryDate: String? = null,
    @SerialName("markedForExport") val markedForExport: Boolean? = null,
    @SerialName("registration") val registration: String? = null,
    @SerialName("engineSize") val engineSize: String? = null,
    @SerialName(value = "id") val id: String = "",
    @SerialName(value = "userId") val userId: String = "",
    @SerialName(value = "createdAt") val createdAt: String = "",
    @SerialName(value = "updatedAt") val updatedAt: String = "",
    @SerialName(value = "deletedAt") val deletedAt: String? = null,
)

@OptIn(InternalSerializationApi::class)
@Serializable
data class MotTest(
    @SerialName("completedDate") val completedDate: String? = null,
    @SerialName("testResult") val testResult: String? = null,
    @SerialName("odometerValue") val odometerValue: String? = null,
    @SerialName("odometerUnit") val odometerUnit: String? = null,
    @SerialName("defects") val defects: List<Defect> = emptyList(),
    @SerialName("registrationAtTimeOfTest") val registrationAtTimeOfTest: String? = null,
    @SerialName("motTestNumber") val motTestNumber: String? = null,
    @SerialName("expiryDate") val expiryDate: String? = null,
    @SerialName("odometerResultType") val odometerResultType: String? = null,
    @SerialName("dataSource") val dataSource: String? = null,
    @SerialName("id") val id: String? = null,
    @SerialName("vehicleId") val vehicleId: String? = null,
    @SerialName("vehicleRegistration") val vehicleRegistration: String? = null,
    @SerialName("vehicleMake") val vehicleMake: String? = null,
    @SerialName("vehicleModel") val vehicleModel: String? = null,
    @SerialName("vehicleYear") val vehicleYear: Int? = null,
    @SerialName("vehicleVin") val vehicleVin: String? = null,
    @SerialName("vehicleEngineCapacity") val vehicleEngineCapacity: Int? = null,
    @SerialName("vehicleFuelType") val vehicleFuelType: String? = null,
    @SerialName("vehicleCo2Emissions") val vehicleCo2Emissions: Int? = null,
    @SerialName("vehicleTypeApproval") val vehicleTypeApproval: String? = null,
    @SerialName("vehicleColour") val vehicleColour: String? = null,
    @SerialName("vehiclePrimaryColour") val vehiclePrimaryColour: String? = null,
    @SerialName("vehicleWheelplan") val vehicleWheelplan: String? = null,
    @SerialName("vehicleRegistrationDate") val vehicleRegistrationDate: String? = null,
    @SerialName("vehicleMonthOfFirstRegistration") val vehicleMonthOfFirstRegistration: String? = null,
    @SerialName("vehicleManufactureDate") val vehicleManufactureDate: String? = null,
    @SerialName("vehicleFirstUsedDate") val vehicleFirstUsedDate: String? = null,
    @SerialName("vehicleDateOfLastV5CIssued") val vehicleDateOfLastV5CIssued: String? = null,
    @SerialName("vehicleTaxStatus") val vehicleTaxStatus: String? = null,
    @SerialName("vehicleTaxDueDate") val vehicleTaxDueDate: String? = null,
    @SerialName("vehicleMotStatus") val vehicleMotStatus: String? = null,
    @SerialName("vehicleHasOutstandingRecall") val vehicleHasOutstandingRecall: String? = null,
    @SerialName("vehicleSalvageCategory") val vehicleSalvageCategory: String? = null,
    @SerialName("vehicleVehicleTier") val vehicleVehicleTier: String? = null,
    @SerialName("vehiclePreviousKeepers") val vehiclePreviousKeepers: Int? = null,
    @SerialName("vehiclePreviousOwners") val vehiclePreviousOwners: Int? = null,
    @SerialName("vehicleSeats") val vehicleSeats: Int? = null,
    @SerialName("vehiclePrice") val vehiclePrice: Double? = null,
    @SerialName("vehicleMaxTowWeight") val vehicleMaxTowWeight: Double? = null,
    @SerialName("serviceHistory") val serviceHistory: String? = null
)

@OptIn(InternalSerializationApi::class)
@Serializable
data class Defect(
    @SerialName("dangerous") val dangerous: Boolean = false,
    @SerialName("text") val text: String? = null,
    @SerialName("type") val type: String? = null,
    @SerialName("id") val id: String? = null,
    @SerialName("vehicleId") val vehicleId: String? = null,
    @SerialName("motTestId") val motTestId: String? = null,
    @SerialName("vehicleRegistration") val vehicleRegistration: String? = null,
    @SerialName("vehicleMake") val vehicleMake: String? = null,
    @SerialName("vehicleModel") val vehicleModel: String? = null,
    @SerialName("vehicleYear") val vehicleYear: Int? = null,
    @SerialName("vehicleVin") val vehicleVin: String? = null,
    @SerialName("vehicleEngineCapacity") val vehicleEngineCapacity: Int? = null,
    @SerialName("vehicleFuelType") val vehicleFuelType: String? = null,
    @SerialName("vehicleCo2Emissions") val vehicleCo2Emissions: Int? = null,
    @SerialName("vehicleTypeApproval") val vehicleTypeApproval: String? = null,
    @SerialName("vehicleColour") val vehicleColour: String? = null,
    @SerialName("vehiclePrimaryColour") val vehiclePrimaryColour: String? = null,
    @SerialName("vehicleWheelplan") val vehicleWheelplan: String? = null,
    @SerialName("vehicleRegistrationDate") val vehicleRegistrationDate: String? = null,
    @SerialName("vehicleMonthOfFirstRegistration") val vehicleMonthOfFirstRegistration: String? = null,
    @SerialName("vehicleManufactureDate") val vehicleManufactureDate: String? = null,
    @SerialName("vehicleFirstUsedDate") val vehicleFirstUsedDate: String? = null,
    @SerialName("vehicleDateOfLastV5CIssued") val vehicleDateOfLastV5CIssued: String? = null,
    @SerialName("vehicleTaxStatus") val vehicleTaxStatus: String? = null,
    @SerialName("vehicleTaxDueDate") val vehicleTaxDueDate: String? = null,
    @SerialName("vehicleMotStatus") val vehicleMotStatus: String? = null,
    @SerialName("vehicleHasOutstandingRecall") val vehicleHasOutstandingRecall: String? = null,
    @SerialName("vehicleSalvageCategory") val vehicleSalvageCategory: String? = null,
    @SerialName("vehicleVehicleTier") val vehicleVehicleTier: String? = null,
    @SerialName("vehiclePreviousKeepers") val vehiclePreviousKeepers: Int? = null,
    @SerialName("vehiclePreviousOwners") val vehiclePreviousOwners: Int? = null,
    @SerialName("vehicleSeats") val vehicleSeats: Int? = null,
    @SerialName("vehiclePrice") val vehiclePrice: Double? = null,
    @SerialName("vehicleMaxTowWeight") val vehicleMaxTowWeight: Double? = null,
    @SerialName(value = "createdAt") val createdAt: String = "",
    @SerialName(value = "updatedAt") val updatedAt: String = "",
    @SerialName(value = "deletedAt") val deletedAt: String? = null,
    @SerialName(value = "userId") val userId: String = "",
)

@OptIn(InternalSerializationApi::class)
@Serializable
data class SymptomReport(
    @SerialName("id") val id: String? = null,
    @SerialName("userDescription") val userDescription: String? = null,
    @SerialName("mechanicScript") val mechanicScript: String? = null,
    @SerialName("vehicleId") val vehicleId: String? = null,
    @SerialName("motTestId") val motTestId: String? = null,
    @SerialName("vehicleRegistration") val vehicleRegistration: String? = null,
    @SerialName("vehicleMake") val vehicleMake: String? = null,
    @SerialName("vehicleModel") val vehicleModel: String? = null,
    @SerialName("vehicleYear") val vehicleYear: Int? = null,
    @SerialName("vehicleVin") val vehicleVin: String? = null,
    @SerialName("vehicleEngineCapacity") val vehicleEngineCapacity: Int? = null,
    @SerialName("vehicleFuelType") val vehicleFuelType: String? = null,
    @SerialName("vehicleCo2Emissions") val vehicleCo2Emissions: Int? = null,
    @SerialName("vehicleTypeApproval") val vehicleTypeApproval: String? = null,
    @SerialName("vehicleColour") val vehicleColour: String? = null,
    @SerialName("vehiclePrimaryColour") val vehiclePrimaryColour: String? = null,
    @SerialName("vehicleWheelplan") val vehicleWheelplan: String? = null,
    @SerialName("vehicleRegistrationDate") val vehicleRegistrationDate: String? = null,
    @SerialName("vehicleMonthOfFirstRegistration") val vehicleMonthOfFirstRegistration: String? = null,
    @SerialName("vehicleManufactureDate") val vehicleManufactureDate: String? = null,
    @SerialName("vehicleFirstUsedDate") val vehicleFirstUsedDate: String? = null,
    @SerialName("vehicleDateOfLastV5CIssued") val vehicleDateOfLastV5CIssued: String? = null,
    @SerialName("vehicleTaxStatus") val vehicleTaxStatus: String? = null,
    @SerialName("vehicleTaxDueDate") val vehicleTaxDueDate: String? = null,
    @SerialName("vehicleMotStatus") val vehicleMotStatus: String? = null,
    @SerialName("vehicleHasOutstandingRecall") val vehicleHasOutstandingRecall: String? = null,
    @SerialName("vehicleSalvageCategory") val vehicleSalvageCategory: String? = null,
    @SerialName("vehicleVehicleTier") val vehicleVehicleTier: String? = null,
    @SerialName("vehiclePreviousKeepers") val vehiclePreviousKeepers: Int? = null,
    @SerialName("vehiclePreviousOwners") val vehiclePreviousOwners: Int? = null,
    @SerialName("vehicleSeats") val vehicleSeats: Int? = null,
    @SerialName("vehiclePrice") val vehiclePrice: Double? = null,
    @SerialName("vehicleMaxTowWeight") val vehicleMaxTowWeight: Double? = null,
)